services:
  # FastAPI Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: jupiter-backend
    restart: always
    env_file:
      - .env                    # Root environment file
      - backend/backend.env    # Backend-specific overrides
    environment:
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-production}
    # No database dependency - DuckDB is embedded
    networks:
      - jupiter-net
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - ./backend/logs:/app/logs
      - ./backups:/app/backups
      - ./data:/app/data  # DuckDB data directory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 20s
      timeout: 5s
      retries: 6

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: jupiter-frontend
    restart: always
    env_file:
      - .env                    # Root environment file
      - frontend/.env          # Frontend-specific overrides
    environment:
      - REACT_APP_API_URL=${API_URL}
      - REACT_APP_ENVIRONMENT=${APP_ENVIRONMENT}
    networks:
      - jupiter-net
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 20s
      timeout: 5s
      retries: 6

volumes:
  jupiter-data:
    driver: local

networks:
  jupiter-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16