# Jupiter SIEM - Prometheus Configuration for Docker Deployment
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jupiter-siem-docker'
    environment: 'production'

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Jupiter SIEM Backend
  - job_name: 'jupiter-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # Jupiter SIEM Frontend
  - job_name: 'jupiter-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Docker Container Metrics (if cAdvisor is available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    honor_labels: true

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 200h
    retention.size: 10GB
    wal-compression: true